### ISSUE TITLE
No documentation that this reaches out to external service

### ISSUE THREAD

**Issue by negentropicdev** [PantherLAB/DependencyInspector#1]
It is absolutely critical that this advertises that it uses an online service for the diagram generation. This could be a huge violation for regulations such as ITAR where internal names for classified / protected things are communicated to an external source.

I *HIGHLY* recommend that a local tool such as graphviz gets used instead.

**Comment by negentropicdev** [comment]
I couldn't see anywhere in the package description that it uses kroki.io (just that error that was posted to forums) but I see the underlying GraphBuilder package provides support for graphviz.

**Comment by enoearias** [comment]
Hi @negentropicdev , I'll investigate this further. In the meantime, I've added a warning to the product description page. This page is shown after the package is installed.

https://pantherlab.github.io/DependencyInspector/

Thank you!

**Comment by enoearias** [comment]
FYI, I´m currently working on the version 2.0.0.11, it will Installs Graphviz using command line winget command, this wil avoid reaching to external services.

https://graphviz.org/download/

CMD: winget install graphviz

**Comment by enoearias** [comment]
New Documentation Updated:
https://pantherlab.github.io/DependencyInspector/

VIP Package:
https://www.vipm.io/package/pantherlab_lib_dependency_inspector/
